const compliments = [
    "The universe clearly upgraded when you arrived",
    "You make complex things look easy",
    "You are a light in the darkest times.",
    "Your smile can brighten anyone's day.",
    "You have a heart that truly cares.",
    "Being around you feels like home.",
    "Your kindness is contagious.",
    "You make people feel seen and valued.",
    "Your presence makes the world better.",
    "You are stronger than you realize.",
    "You inspire others just by being you.",
    "Your courage is admirable.",
    "You bring out the best in people.",
    "Your laughter is infectious.",
    "You are a beautiful soul.",
    "You have an incredible way with words.",
    "You make a difference without even trying.",
    "Your positivity lights up the room.",
    "You are genuinely irreplaceable.",
    "Your empathy is rare and precious.",
    "You have a warmth that draws people in.",
    "Your creativity knows no bounds.",
    "You have a magical way of making people smile.",
    "Your honesty is refreshing.",
    "You are a gift to those around you.",
    "You radiate calm and reassurance.",
    "You make everyone feel comfortable.",
    "Your energy is uplifting.",
    "You are deeply appreciated more than you know.",
    "Your compassion is inspiring.",
    "You have a beautiful way of seeing the world.",
    "Your patience is remarkable.",
    "You are brave in ways most dont notice.",
    "You make ordinary moments extraordinary.",
    "Your understanding is profound.",
    "You have a gentle strength.",
    "Your spirit is truly uplifting.",
    "You are full of wisdom and insight.",
    "Your confidence is inspiring.",
    "You have a soul that shines bright.",
    "You are thoughtful in everything you do.",
    "Your generosity is unmatched.",
    "You have a spark that cant be dimmed.",
    "You make others feel valued and loved.",
    "Your curiosity is beautiful.",
    "You have a heart full of gold.",
    "You bring joy wherever you go.",
    "You are wonderfully unique.",
    "Your optimism is contagious.",
    "You make life feel lighter.",
    "You are deeply cherished.",
    "Your guidance is invaluable.",
    "You have an amazing sense of humor.",
    "You are patient and understanding.",
    "Your soul is kind and gentle.",
    "You are worthy of all good things.",
    "You make the world feel safer.",
    "You inspire trust and confidence.",
    "You are an extraordinary human being.",
    "Your perseverance is admirable.",
    "You make challenges look manageable.",
    "You have a wonderful way of connecting with people.",
    "Your insight is invaluable.",
    "You have a beautiful inner strength.",
    "You are thoughtful and considerate.",
    "You have a knack for making people feel special.",
    "You are deeply loved.",
    "You radiate peace and serenity.",
    "You have a beautiful mind.",
    "You are an incredible listener.",
    "Your words have power.",
    "You have a warmth that comforts.",
    "You are full of grace and dignity.",
    "Your integrity is admirable.",
    "You bring calm into chaos.",
    "You are an amazing friend.",
    "You make life brighter with your presence.",
    "Your heart is pure and kind.",
    "You have a remarkable soul.",
    "You are a true treasure.",
    "You are endlessly patient and understanding.",
    "You are thoughtful beyond words.",
    "Your authenticity is inspiring.",
    "You are wonderfully empathetic.",
    "Your soul is radiant.",
    "You make people feel safe and seen.",
    "You have a beautiful way of expressing yourself.",
    "You are deeply inspiring.",
    "You are a source of joy.",
    "Your presence is soothing.",
    "You are a beacon of hope.",
    "You have a remarkable inner beauty.",
    "You are full of light and love.",
    "Your spirit lifts others up.",
    "You are incredibly thoughtful.",
    "You make a lasting impact on people.",
    "Your soul is kind and loving.",
    "You are a true blessing.",
    "You make the world a more beautiful place.",
    "You have an amazing ability to understand others.",
    "You are gentle yet strong.",
    "You are inspiring in subtle ways.",
    "Your heart touches everyone around you.",
    "You are truly remarkable.",
    "You are full of love and warmth.",
    "You bring out the best in everyone.",
    "You are a gift in every sense of the word."

];

const button = document.getElementById("btn");
const complimentText = document.getElementById("compliment");

let lastIndex = -1;

function getRandomCompliment() {
    let randomIndex;

    do {
        randomIndex = Math.floor(Math.random() * compliments.length);
    } while (randomIndex === lastIndex);

    complimentText.textContent = compliments[randomIndex];

    lastIndex = randomIndex;
    }

button.addEventListener("click", getRandomCompliment);